- name: Set GRUB timeout to 0
  hosts: localhost
  sudo: yes

  tasks:
  - name: Insert line into /etc/default/grub
    lineinfile: dest=/etc/default/grub regexp='^GRUB_TIMEOUT=' line='GRUB_TIMEOUT=0'

  - name: Update GRUB
    command: update-grub
