- name: Perform setup on all machines
  hosts:
  - localhost
  sudo: yes
  tasks:
  - name: Add PPA martin-ueding/stable
    apt_repository: >
        repo='ppa:martin-ueding/stable'
        state=present

  - name: Install packages
    action: apt pkg={{ item }} state=installed
    with_items:

    - apt-file
    - awesome
    - awesome-extra
    - backup-scripts
    - bogomips
    - enigmail
    - filezilla
    - firefox
    - fish
    - gstreamer0.10-plugins-bad
    - gufw
    - hardinfo
    - htop
    - imagemagick
    - inkscape
    - konversation
    - legacy-file-formats
    - lock-and-off
    - maintenance
    - pavucontrol
    - pinentry-qt4
    - python3-termcolor
    - qrencode
    - task
    - thunderbird-locale-de
    - tree
    - unwrap-pdf-to-jpeg
    - vim
    - vlc
    - vnstat
    - xournal
    - youtube-dl
#    - kde-wallpapers
#    - kdewallpapers
#    - ubuntu-gnome-wallpapers
#    - ubuntu-wallpapers

  - name: Remove Amazon Shopping Lens
    apt: name=unity-webapps-common state=absent purge=yes

  - name: Set shell to fish
    user: name=mu shell=/usr/bin/fish

  - name: Remove Flash Player
    apt: name=flashplugin-installer state=absent purge=yes

- name: Perform setup on main computer
  hosts:
  - localhost
  sudo: yes

  tasks:
  - name: Install packages
    action: apt pkg={{ item }} state=installed
    with_items:

    - a4-scan
    - clementine
    - fatrat
    - gimp
    - mediathekview
    - mp3-packer
    - pdftk
    - thinkpad-scripts
    - uni-tools
    - virtualbox
    - virtualbox-qt
    - whois
