# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: martin-friese
  hosts: localhost
  sudo: yes
  roles:
  - role: charge-limits
    start: 80
    stop: 85
    state: present
  - ansible-master
  - fix-gnome-keyring
  - automatic-upgrades
  - dev-latex
  - dev-programming
  - dev-packaging
  - mu-conf
  - mu-conf-main
  - martin-hydrogen-backup
  - role: flash
    state: absent
  - role: ubuntu-release-upgrades
    lts: false
  - role: battery-health
    state: absent
  - role: lightdm-background
    url: https://farm6.staticflickr.com/5302/5742972261_5c80c1d374_o_d.jpg
    suffix: jpg
