# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: martin-friese
  hosts: localhost
  sudo: yes
  roles:
  - ansible-master
  - fix-gnome-keyring
  - role: apt-cacher-client
    state: absent
  - automatic-upgrades
  - dev-latex
  - dev-programming
  - mu-conf
  - mu-conf-main
  - martin-hydrogen-backup
  - role: flash
    state: absent
