# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: martin-gelderland
  hosts: martin-gelderland.local
  roles:
  - role: smokeping
    sections:
      Local:
      - fritz.box
      - localhost
      Internet:
      - chaos.stw-bonn.de
      - martin-ueding.de
      - spiegel.de
      - unitymedia.de
  - dev-programming
  - apt-cacher-server
  - mu-and-fs
  - shopping-list
