# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: martin-friese
  hosts: localhost
  sudo: yes
  roles:
  - apt-cacher-client
  - dev-latex
  - dev-programming
  - martin-ueding-settings
