# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: martin-gelderland
  hosts: martin-gelderland.local
  roles:
  - role: radicale
    tags: caldav

  - role: apt-cacher-server
    state: absent

  - suspend-hdd

  - role: smokeping
    sections:
      Internet:
      - [martin-ueding, martin-ueding.de]
      - [chaos, chaos.stw-bonn.de]
      - [spiegel, spiegel.de]
      - [unitymedia, unitymedia.de]
      - [telekom-dns, 217.5.100.185]
      Local:
      - [localhost, localhost]
      - [Router, fritz.box]

 #- dev-programming
  - file-server
  - mu-and-fs
  - role: shopping-list
    tags: shopping-list

  - mysql-server

  - gelderland-backup

  - role: jnv.unattended-upgrades
    unattended_origins_patterns:
    - 'o=Raspbian,a=stable'
    - 'o=Raspbian,a=stable-updates'
    - 'o=Raspbian,a=proposed-updates'
    - 'o=Raspbian,a=stable,label=Raspbian-Security'
  
    unattended_package_blacklist: []
    unattended_autofix_interrupted_dpkg: true
    unattended_minimal_steps: true
    unattended_install_on_shutdown: false
    unattended_remove_unused_dependencies: false
    unattended_automatic_reboot: false
