- hosts:
  - towers
  sudo: yes
  tasks:
  - name: Install personal base packages
    action: apt pkg={{ item }} state=installed
    with_items:
    - awesome
    - awesome-extra
    - backup-scripts
    - bogomips
    - enigmail
    - filezilla
    - firefox
    - fish
    - hardinfo
    - htop
    - imagemagick
    - inkscape
    - lock-and-off
    - maintenance
    - pavucontrol
    - pinentry-qt4
    - task
    - vim
    - vnstat
    - xournal
    - youtube-dl

  - name: Remove Amazon Shopping Lens
    apt: name=unity-webapps-common state=absent purge=yes

  - name: Add PPA martin-ueding/stable
    apt_repository: >
        repo='ppa:martin-ueding/stable'
        state=present
