# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: martin-gelderland
  hosts: martin-gelderland.local
  roles:
  - role: smokeping
    sections:
      Local:
      - [Router, fritz.box]
      - [localhost, localhost]
      Internet:
      - [chaos, chaos.stw-bonn.de]
      - [martin-ueding, martin-ueding.de]
      - [spiegel, spiegel.de]
      - [unitymedia, unitymedia.de]
  - dev-programming
  - apt-cacher-server
  - mu-and-fs
  - shopping-list
