- hosts:
  - localhost
  sudo: yes
  tasks:
  - name: Add PPA martin-ueding/stable
    apt_repository: >
        repo='ppa:martin-ueding/stable'
        state=present
        
  - name: Install personal base packages
    action: apt pkg={{ item }} state=installed
    with_items:

    - awesome
    - awesome-extra
    - backup-scripts
    - bogomips
    - enigmail
    - filezilla
    - firefox
    - fish
    - gufw
    - hardinfo
    - htop
    - imagemagick
    - inkscape
    - lock-and-off
    - maintenance
    - pavucontrol
    - pinentry-qt4
    - task
    - thunderbird-locale-de
    - vim
    - vnstat
    - xournal
    - youtube-dl

  - name: Remove Amazon Shopping Lens
    apt: name=unity-webapps-common state=absent purge=yes
        
  - name: Set shell to fish
    user: name=mu shell=/usr/bin/fish
    
  - name: Remove Flash Player
    apt: name=flashplugin-installer state=absent purge=yes

- hosts:
  - localhost
  sudo: yes

  - name: Install packages to enhance Kubuntu
    action: apt pkg={{ item }} state=installed
    with_items:

    - clementine
    - thinkpad-scripts
