- hosts:
  - localhost
  sudo: yes
  tasks:
  - name: Add PPA martin-ueding/stable
    apt_repository: >
        repo='ppa:martin-ueding/stable'
        state=present

  - name: Install personal base packages
    action: apt pkg={{ item }} state=installed
    with_items:

    - awesome
    - awesome-extra
    - backup-scripts
    - bogomips
    - enigmail
    - filezilla
    - firefox
    - fish
    - gstreamer0.10-plugins-bad
    - gufw
    - hardinfo
    - htop
    - imagemagick
    - inkscape
    - kde-wallpapers
    - kdewallpapers
    - konversation
    - legacy-file-formats
    - lock-and-off
    - maintenance
    - pavucontrol
    - pinentry-qt4
    - qrencode
    - task
    - thunderbird-locale-de
    - ubuntu-gnome-wallpapers
    - ubuntu-wallpapers
    - vim
    - vnstat
    - xournal
    - youtube-dl

  - name: Remove Amazon Shopping Lens
    apt: name=unity-webapps-common state=absent purge=yes

  - name: Set shell to fish
    user: name=mu shell=/usr/bin/fish

  - name: Remove Flash Player
    apt: name=flashplugin-installer state=absent purge=yes

- hosts:
  - localhost
  sudo: yes

  tasks:
  - name: Install packages I want on my main computer
    action: apt pkg={{ item }} state=installed
    with_items:

    - a4-scan
    - clementine
    - fatrat
    - mediathekview
    - thinkpad-scripts
