# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install radicale
  apt: name=radicale state=installed

- name: Install python-pam
  apt: name=python-pam state=installed

- name: Create first link from PAM to pam
  file:
    path: /usr/lib/python2.7/dist-packages/pammodule.so
    src: /usr/lib/python2.7/dist-packages/PAMmodule.so
    state: link

- name: Create second link from PAM to pam
  file:
    path: /usr/lib/pyshared/python2.7/pammodule.so
    src: /usr/lib/pyshared/python2.7/PAMmodule.so
    state: link

- name: Install configuration file
  template:
    src: config.j2
    dest: /etc/radicale/config
    mode: 0644
    owner: root
    group: root
  notify:
  - Restart radicale
