# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install radicale
  apt: name=radicale state=installed

- name: Install python-passlib
  apt: name=python-passlib state=installed

- name: Create user mu
  htpasswd:
    create: yes
    name: mu
    password: test
    path: '{{ htpasswd_filename }}'

- name: Install configuration file
  template:
    src: config.j2
    dest: /etc/radicale/config
    mode: 0644
    owner: root
    group: root
  notify:
  - Restart radicale
