# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Install packages
  action: apt pkg={{ item }} state=installed
  with_items:

  - a4-scan
  - akonadi-backend-sqlite
  - awesome
  - awesome-extra
  - backup-scripts
  - clementine
  - enigmail
  - fatrat
  - gimp
  - imagemagick
  - inkscape
  - k4dirstat
  - keepassx
  - konversation
  - legacy-file-formats
  - lock-and-off
  - maintenance
  - mediathekview
  - mp3-packer
  - pavucontrol
  - pdftk
  - pinentry-qt4
  - python3-termcolor
  - qrencode
  - scantailor
  - taskwarrior
  - thunderbird-locale-de
  - uni-tools
  - unison-gtk
  - unwrap-pdf-to-jpeg
  - viking
  - whois
  - xournal
  - zbar-tools

- name: Install thinkpad-scripts
  when: ansible_product_version | search('ThinkPad')
  apt: pkg=thinkpad-scripts state=installed

- name: Install virtualization packages
  when: ansible_virtualization_role == 'host'
  action: apt pkg={{ item }} state=installed
  with_items:
  - virtualbox
  - virtualbox-qt
