# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: Install packages
  action: apt pkg={{ item }} state=installed
  with_items:

  - a4-scan
  - backup-scripts
  - clementine
  - enigmail
  - fatrat
  - gimp
  - inkscape
  - keepassx
  - maintenance
  - mediathekview
  - mp3-packer
  - pdftk
  - scantailor
  - task
  - thunderbird-locale-de
  - uni-tools
  - unison-gtk
  - viking
  - whois
  - zbar-tools

- name: Install thinkpad-scripts
  when: ansible_product_version | search('ThinkPad')
  apt: pkg=thinkpad-scripts state=installed

- name: Install virtualization packages
  when: ansible_virtualization_role == 'host'
  action: apt pkg={{ item }} state=installed
  with_items:
  - virtualbox
  - virtualbox-qt
