# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install packages
  action: apt pkg={{ item }} state=installed
  with_items:

  - a4-scan
  - clementine
  - fatrat
  - gimp
  - inkscape
  - keepassx
  - mediathekview
  - mp3-packer
  - pdftk
  - scantailor
  - uni-tools
  - viking
  - whois

- name: Install thinkpad-scripts
  when: ansible_product_version | search('ThinkPad')
  apt: pkg=thinkpad-scripts state=installed

- name: Install virtualization packages
  when: ansible_virtualization_role == 'host'
  action: apt pkg={{ item }} state=installed
  with_items:
  - virtualbox
  - virtualbox-qt
