# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install MySQL server
  apt: name=mysql-server state=present

- name: Copy cron job
  cron:
    name: MySQL dump
    job: 'mysqldump -u root -p{{ mysql_root_passwd }} --all-databases | gzip > /var/backups/mysql/$(date -u +%FT%T).sql.gz'
    hour: 1
    state: present
