# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: apt
  when: ansible_pkg_mgr == 'apt'
  include: apt.yml

- name: yum
  when: ansible_pkg_mgr == 'yum'
  include: yum.yml

- name: zypper
  when: ansible_pkg_mgr == 'zypper'
  include: zypper.yml

- name: Ubuntu
  when: ansible_distribution == "Ubuntu"
  include: ubuntu.yml

- name: Fedora
  when: ansible_distribution == 'Fedora'
  include: fedora.yml

- name: Check for fish shell
  stat: path=/usr/bin/fish
  register: usr_bin_fish

- name: Set shell to fish if it exists
  when: ansible_distribution != "Debian" and usr_bin_fish.stat.exists
  user: name=mu shell=/usr/bin/fish

- name: Set shell to bash
  when: not usr_bin_fish.stat.exists
  user: name=mu shell=/bin/bash
