# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: apt
  when: ansible_pkg_mgr == 'apt'
  include: apt.yml

- name: Ubuntu
  when: ansible_distribution == "Ubuntu"
  include: ubuntu.yml

- name: Set shell to fish
  when: ansible_distribution == "Ubuntu"
  user: name=mu shell=/usr/bin/fish
