# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add PPA martin-ueding/stable
  apt_repository:
    repo: 'ppa:martin-ueding/stable'
    state: present

- name: Install Ubuntu specific packages
  action: apt pkg={{ item }} state=installed
  with_items:

  - bogomips
  - fish

- name: Enable color prompt for everyone
  lineinfile:
    dest: /etc/skel/.bashrc
    state: present
    regexp: '#force_color_prompt=yes'
    line: 'force_color_prompt=yes'
