# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Install Open Build Service repository
  when: ansible_distribution_version == '13.2'
  zypper_repository:
    repo: http://download.opensuse.org/repositories/home:/martinueding/openSUSE_13.2/home:martinueding.repo
    state: present


- name: zypper
  action: zypper name={{ item }} state=installed
  with_items:

    - mlocate
