# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Install squid
  apt: name=squid3 state=present

- name: Install config
  template:
    src: squid.conf.j2
    dest: /etc/squid3/squid.conf
  notify:
    - Restart squid3
