# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Disable GDM
  service: name=gdm state=stopped enabled=no
  ignore_errors: yes

- name: Disable KDM
  service: name=kdm state=stopped enabled=no
  ignore_errors: yes

- name: Disable LightDM
  service: name=lightdm state=stopped enabled=no
  ignore_errors: yes

- name: Enable SDDM
  service: name=sddm state=started enabled=yes
