# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- hosts: all
  sudo: yes
  roles:
  - role: jnv.unattended-upgrades
    when: ansible_distribution == "Ubuntu"
    unattended_origins_patterns: []
    unattended_package_blacklist: []
    unattended_autofix_interrupted_dpkg: true
    unattended_minimal_steps: true
    unattended_install_on_shutdown: false
    unattended_remove_unused_dependencies: true
    unattended_automatic_reboot: false
