# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Fedora
  include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: openSUSE
  include: opensuse.yml
  when: ansible_distribution == 'Suse'
