# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add new user
user:
    name: tutoring
    password: '{{ password }}'
    update_password: on_create

- name: Download Debian package
  get_url:
    url: http://www.bluej.org/download/files/bluej-314b.deb
    dest: /tmp/bluej.deb

- name: Install Debian package
  apt:
    deb: /tmp/bluej.deb
    state: present
