# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add new user
  user:
    name: tutoring
    password: "{{ lookup('file', '~/.secrects/tutoring-hash.txt') }}"
    update_password: on_create
    shell: /bin/bash
    comment: CS Tutoring,,,

- name: Test for BlueJ
  shell: apt-cache show bluej | grep installed
  register: bluej_check
  ignore_errors: True

- name: Download Debian package
  when: bluej_check|failed
  get_url:
    url: http://www.bluej.org/download/files/bluej-314b.deb
    dest: /tmp/bluej.deb

- name: Install Debian package
  when: bluej_check|failed
  apt:
    deb: /tmp/bluej.deb
    state: installed
