# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Add users
  user:
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    password: '{{ item.hash }}'
  with_items: linux_users
