# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Add Martin Ueding
  user:
    name: mu
    comment: "Martin Ueding"
    password: ***REMOVED***

- name: Add ***REMOVED***
  user: >
    name: fs
    comment: "***REMOVED***"
    password: ***REMOVED***
