# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: Add users
  user:
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    password: '{{ item.hash }}'
    groups: '{{ item.groups }}'
    append: yes
    update_password: on_create
    createhome: yes
  with_items: linux_users
