# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: Add users
  user:
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    password: "{{ lookup('file', '~/.secrects/' + item.name + '-hash.txt') }}"
    groups: '{{ item.groups }}'
    append: yes
    update_password: on_create
    createhome: yes
  with_items: 
    - name: mu
      comment: Martin Ueding,,,
      groups: adm,cdrom,sudo,plugdev
    - name: fs
      comment: Frederike Schrödel,,,
      groups:
