# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install packages
  action: apt pkg={{ item }} state=present
  with_items:

  - apache2
  - filezilla
  - libapache2-mod-php5
  - mysql-server
  - php5-mysql
  - python-django
  - ruby-sass

- name: Create MySQL database
  mysql_db:
    name: develop
    state: present
    login_user: root
    login_password: ""

- name: Create MySQL user
  mysql_user:
    name: develop
    password: develop
    state: present
    priv: develop.*:ALL,GRANT
    login_user: root
    login_password: ""
