# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add PPA
  apt_repository: repo=ppa:morgwai/tpbat state=absent

- name: Add PPA for trusty
  apt_repository:
    repo: deb http://ppa.launchpad.net/morgwai/tpbat/ubuntu trusty main
    state: present

- name: Install tpacpi-bat
  apt: name=tpacpi-bat state=installed

- name: Set start threshold
  cron:
    name: start-threshold
    job: tpacpi-bat -s ST 0 {{ start }}
    special_time: reboot
    state: '{{ state }}'
  notify: start-threshold

- name: Set stop threshold
  cron:
    name: stop-threshold
    job: tpacpi-bat -s SP 0 {{ stop }}
    special_time: reboot
    state: '{{ state }}'
  notify: stop-threshold

- name: Install `full-charge` script
  template:
    src: full-charge.j2
    dest: /usr/local/bin/full-charge
    mode: 0755
    owner: root
    group: root
  when: state == 'present'
