# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Update policy
  when: ansible_distribution == 'Ubuntu'
  lineinfile:
    dest: /etc/update-manager/release-upgrades
    regexp: ^Prompt=
    line: Prompt={{ 'lts' if lts else 'normal' }}
