# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install apt-cacher-ng
  apt: pkg=apt-cacher-ng state=installed

- name: Copy config file
  template: src=01proxy.j2 dest=/etc/apt/apt.conf.d/01proxy
