# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Copy suspend-usb-hdd script
  copy: src=suspend-usb-hdd dest=/usr/local/bin/ mode=755

- name: Install cron job
  cron: 
    name: Suspend USB HDD
    job: /usr/local/bin/suspend-usb-hdd
    minute: '*/5'
    state: present
