# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Copy suspend-usb-hdd script
  copy: src=suspend-usb-hdd dest=/usr/local/bin/ mode=755

- name: Install cron job
  template: src=cronjob.j2 dest=/etc/cron.d/ owner=root mode=600
