# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add Kodi PPA
  apt_repository: repo=ppa:team-xbmc/ppa state=present

- name: Install kodi
  apt: name=kodi state=installed

- name: Let Kodi start automatically
  lineinfile:
    dest: /home/watching/.config/lxsession/LXDE/autostart
    owner: watching
    create: yes
    line: kodi
    state: absent

- name: Create autostart folder
  file:
    dest: /home/watching/.config/autostart
    state: directory

- name: Install desktop file
  copy:
    src: kodi.desktop
    dest: /home/watching/.config/autostart/kodi.desktop
    owner: watching
