# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add user account for watching
  user:
    name: watching
    comment: Watching,,,
    state: present
    generate_ssh_key: yes
    password: $6$FnGs0B0kp$KpYTkhtiVjqQXCu6I7HZO46MekTvxQlRMw.PlZAnTwC14NY6bl6c/ulUBFj3h4PgZbc4W.5nwwVxB4NKwyWBU1
    update_password: always

- include: auto-login.yml

- name: Allow mu@martin-friese to log in
  authorized_key:
    user: watching
    key: "{{ lookup('file', '/home/mu/.ssh/id_rsa.pub') }}"
    state: present
