# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Create user account for Jan
  user:
    name: janweber
    password: "{{ lookup('file', '~/.secrects/janweber-hash.txt') }}"
    shell: /bin/bash
    update_password: on_create
    comment: Jan Maria Weber,,,

- name: Install LaTeX IDEs
  action: apt pkg={{ item }} state=installed
  with_items:
    - texmaker
    - texstudio
