# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>
- user:
    name: janweber
    password: '{{ janweber_password_hash }}'
    shell: /bin/bash
    update_password: on_create
    comment: Jan Maria Weber,,,
