# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Add cron entry
  cron:
    name: battery-health
    job: battery-health
    user: mu
    state: '{{ state }}'
    minute: '*/5'
    hour: '*'
    day: '*'
    month: '*'
    weekday: '*'
