# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: Install needed packages
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - python-django
    - python-mysqldb
    - sqlite3

- name: Install WSGI script
  template: src=wsgi.j2 dest=/etc/apache2/conf-available/shopping-list.conf
  notify:
    - Restart Apache

- name: Enable config snippet
  file:
    src: /etc/apache2/conf-available/shopping-list.conf
    dest: /etc/apache2/conf-enabled/shopping-list.conf
    state: link

- name: Create database configuration directory
  file: path=/etc/shopping-list/ state=directory

# https://code.djangoproject.com/wiki/NewbieMistakes#DjangosaysUnabletoOpenDatabaseFilewhenusingSQLite3
- name: Ensure that the database directory exists
  file:
    path: '{{ sqlite_dir }}'
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Ensure that the database file exists
  file:
    path: '{{ sqlite_path }}'
    state: file
    owner: www-data
    group: www-data
    mode: 0644

- name: Install database configuration file
  template:
    src: databases.js.j2
    dest: /etc/shopping-list/databases.js
    owner: www-data
    group: www-data
    mode: 0600
  notify:
    - Restart Apache

- name: Checkout git repo
  git:
    repo: https://github.com/martin-ueding/shopping-list-site.git
    dest: /opt/shopping-list-site
    version: master
  notify:
    - Restart Apache

- name: Disable debugging
  lineinfile:
    dest: /opt/shopping-list-site/shoppinglistsite/settings.py
    regexp: '^DEBUG = '
    line: 'DEBUG = False'
  notify:
    - Restart Apache

- name: Ensure that all the Python files belong to www-data
  file:
    path: /opt/shopping-list-site
    owner: www-data
    group: www-data
    recurse: yes

- name: Run collectstatic
  django_manage:
    app_path: /opt/shopping-list-site
    command: collectstatic
