# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install Apache
  apt: name=apache2 state=present

- name: Install WSGI script
  template: src=wsgi.j2 dest=/etc/apache2/conf.d/shopping-list
  notify:
  - Restart Apache

- name: Create database configuration directory
  file: path=/etc/shopping-list/ state=directory

- name: Install database configuration file
  template:
    src: databases.js.j2
    dest: /etc/shopping-list/databases.js
    owner: www-data
    group: www-data
    mode: 0644
  notify:
  - Restart Apache

- name: Checkout git repo
  git:
    repo: https://github.com/martin-ueding/shopping-list-site.git
    dest: /opt/shopping-list-site
    version: django-1.4
  notify:
  - Restart Apache

- name: Copy static files
  command: python manage.py collectstatic --noinput
  args:
    chdir: /opt/shopping-list-site

# TODO Add MySQL user
