# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: Install needed packages
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - python-django
    - python-mysqldb
    - sqlite3

- name: Install WSGI script
  template: src=wsgi.j2 dest=/etc/apache2/conf.d/shopping-list
  notify:
    - Restart Apache

- name: Create database configuration directory
  file: path=/etc/shopping-list/ state=directory

- name: Ensure that the database directory exists
  file:
    path: '{{ sqlite_dir }}'
    state: directory
    owner: www-data
    group: www-data
    mode: 0644

- name: Ensure that the database file exists
  file:
    path: '{{ sqlite_path }}'
    state: file
    owner: www-data
    group: www-data
    mode: 0644

- name: Install database configuration file
  template:
    src: databases.js.j2
    dest: /etc/shopping-list/databases.js
    owner: www-data
    group: www-data
    mode: 0600
  notify:
    - Restart Apache

- name: Checkout git repo
  git:
    repo: https://github.com/martin-ueding/shopping-list-site.git
    dest: /opt/shopping-list-site
    version: master
  notify:
    - Restart Apache

- name: Disable debugging
  when: false
  lineinfile:
    dest: /opt/shopping-list-site/shoppinglistsite/settings.py
    regexp: '^DEBUG = '
    line: 'DEBUG = False'
  notify:
    - Restart Apache

- name: Copy static files
  command: python manage.py collectstatic --noinput
  args:
    chdir: /opt/shopping-list-site
