# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install daily script
  template:
    src: gelderland-backup.j2
    dest: /usr/bin/gelderland-backup
    mode: 0755

- name: Install cron job
  cron:
    name: Gelderland Backup
    job: '/usr/bin/gelderland-backup'
    hour: 16
    weekday: 0
    state: present
