# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install common packages
  action: apt name={{ item }} state=installed
  with_items:

  - astyle
  - boxes
  - copyright-updater
  - exuberant-ctags
  - fastplot
  - fonts-droid
  - git
  - git-gui
  - git-ignore-untracked
  - gitk
  - ohcount
  - project-tools
  - python3-dateutil
  - python3-docutils
  - python3-matplotlib
  - python3-numpy
  - python3-prettytable
  - python3-scipy
  - python3-sphinx
  - python3-unitprint
  - template-spawner
  - vim-gtk
