# Copyright © 2014-2015 Martin Ueding <dev@martin-ueding.de>

- name: Ubuntu
  when: ansible_distribution == 'Ubuntu'
  include: ubuntu.yml

- name: apt
  when: ansible_pkg_mgr == 'apt'
  include: apt.yml

- name: zypper
  when: ansible_pkg_mgr == 'zypper'
  include: zypper.yml
