# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

- name: Install common packages
  action: apt name={{ item }} state=installed
  with_items:

  - copyright-updater
  - fastplot
  - git-ignore-untracked
  - project-tools
  - python3-unitprint
  - template-spawner
