# Copyright © 2014 Martin Ueding <dev@martin-ueding.de>

- name: Install Samba 3
  apt: name=samba state=present

- name: Install smb.conf
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf validate='testparm -s %s'
  notify:
  -  Restart samba
